// *** WARNING: this file was generated by pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Genezio.Domain.Outputs
{

    [OutputType]
    public sealed class AuthenticationProviders
    {
        public readonly bool? Email;
        public readonly Outputs.GoogleProvider? Google;
        public readonly bool? Web3;

        [OutputConstructor]
        private AuthenticationProviders(
            bool? email,

            Outputs.GoogleProvider? google,

            bool? web3)
        {
            Email = email;
            Google = google;
            Web3 = web3;
        }
    }
}
