// *** WARNING: this file was generated by pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Genezio.Domain.Outputs
{

    [OutputType]
    public sealed class GoogleProvider
    {
        public readonly string Id;
        public readonly string Secret;

        [OutputConstructor]
        private GoogleProvider(
            string id,

            string secret)
        {
            Id = id;
            Secret = secret;
        }
    }
}
