// *** WARNING: this file was generated by pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Genezio.Domain.Inputs
{

    public sealed class AuthenticationProvidersArgs : global::Pulumi.ResourceArgs
    {
        [Input("email")]
        public Input<bool>? Email { get; set; }

        [Input("google")]
        public Input<Inputs.GoogleProviderArgs>? Google { get; set; }

        [Input("web3")]
        public Input<bool>? Web3 { get; set; }

        public AuthenticationProvidersArgs()
        {
        }
        public static new AuthenticationProvidersArgs Empty => new AuthenticationProvidersArgs();
    }
}
