// *** WARNING: this file was generated by pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Genezio.Domain.Inputs
{

    public sealed class EnvironmentVariableArgs : global::Pulumi.ResourceArgs
    {
        public EnvironmentVariableArgs()
        {
        }
        public static new EnvironmentVariableArgs Empty => new EnvironmentVariableArgs();
    }
}
