// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";

export namespace domain {
    export interface AuthenticationProviders {
        email?: boolean;
        google?: outputs.domain.GoogleProvider;
        web3?: boolean;
    }

    export interface EnvironmentVariable {
        name: string;
        value: string;
    }

    export interface GoogleProvider {
        id: string;
        secret: string;
    }

    export interface Project {
        name: string;
        region: string;
    }

}
