# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

from . import _utilities
import typing
# Export this package's modules as members:
from .database import *
from .provider import *
from .serverless_function import *

# Make subpackages available:
if typing.TYPE_CHECKING:
    import pulumi_genezio.domain as __domain
    domain = __domain
else:
    domain = _utilities.lazy_import('pulumi_genezio.domain')

_utilities.register(
    resource_modules="""
[
 {
  "pkg": "genezio",
  "mod": "index",
  "fqn": "pulumi_genezio",
  "classes": {
   "genezio:index:Database": "Database",
   "genezio:index:ServerlessFunction": "ServerlessFunction"
  }
 }
]
""",
    resource_packages="""
[
 {
  "pkg": "genezio",
  "token": "pulumi:providers:genezio",
  "fqn": "pulumi_genezio",
  "class": "Provider"
 }
]
"""
)
