// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package domain

import (
	"context"
	"reflect"

	"example.com/pulumi-genezio/sdk/go/genezio/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

var _ = internal.GetEnvOrDefault

type AuthenticationProviders struct {
	Email  *bool           `pulumi:"email"`
	Google *GoogleProvider `pulumi:"google"`
	Web3   *bool           `pulumi:"web3"`
}

// AuthenticationProvidersInput is an input type that accepts AuthenticationProvidersArgs and AuthenticationProvidersOutput values.
// You can construct a concrete instance of `AuthenticationProvidersInput` via:
//
//	AuthenticationProvidersArgs{...}
type AuthenticationProvidersInput interface {
	pulumi.Input

	ToAuthenticationProvidersOutput() AuthenticationProvidersOutput
	ToAuthenticationProvidersOutputWithContext(context.Context) AuthenticationProvidersOutput
}

type AuthenticationProvidersArgs struct {
	Email  pulumi.BoolPtrInput    `pulumi:"email"`
	Google GoogleProviderPtrInput `pulumi:"google"`
	Web3   pulumi.BoolPtrInput    `pulumi:"web3"`
}

func (AuthenticationProvidersArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*AuthenticationProviders)(nil)).Elem()
}

func (i AuthenticationProvidersArgs) ToAuthenticationProvidersOutput() AuthenticationProvidersOutput {
	return i.ToAuthenticationProvidersOutputWithContext(context.Background())
}

func (i AuthenticationProvidersArgs) ToAuthenticationProvidersOutputWithContext(ctx context.Context) AuthenticationProvidersOutput {
	return pulumi.ToOutputWithContext(ctx, i).(AuthenticationProvidersOutput)
}

func (i AuthenticationProvidersArgs) ToAuthenticationProvidersPtrOutput() AuthenticationProvidersPtrOutput {
	return i.ToAuthenticationProvidersPtrOutputWithContext(context.Background())
}

func (i AuthenticationProvidersArgs) ToAuthenticationProvidersPtrOutputWithContext(ctx context.Context) AuthenticationProvidersPtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(AuthenticationProvidersOutput).ToAuthenticationProvidersPtrOutputWithContext(ctx)
}

// AuthenticationProvidersPtrInput is an input type that accepts AuthenticationProvidersArgs, AuthenticationProvidersPtr and AuthenticationProvidersPtrOutput values.
// You can construct a concrete instance of `AuthenticationProvidersPtrInput` via:
//
//	        AuthenticationProvidersArgs{...}
//
//	or:
//
//	        nil
type AuthenticationProvidersPtrInput interface {
	pulumi.Input

	ToAuthenticationProvidersPtrOutput() AuthenticationProvidersPtrOutput
	ToAuthenticationProvidersPtrOutputWithContext(context.Context) AuthenticationProvidersPtrOutput
}

type authenticationProvidersPtrType AuthenticationProvidersArgs

func AuthenticationProvidersPtr(v *AuthenticationProvidersArgs) AuthenticationProvidersPtrInput {
	return (*authenticationProvidersPtrType)(v)
}

func (*authenticationProvidersPtrType) ElementType() reflect.Type {
	return reflect.TypeOf((**AuthenticationProviders)(nil)).Elem()
}

func (i *authenticationProvidersPtrType) ToAuthenticationProvidersPtrOutput() AuthenticationProvidersPtrOutput {
	return i.ToAuthenticationProvidersPtrOutputWithContext(context.Background())
}

func (i *authenticationProvidersPtrType) ToAuthenticationProvidersPtrOutputWithContext(ctx context.Context) AuthenticationProvidersPtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(AuthenticationProvidersPtrOutput)
}

type AuthenticationProvidersOutput struct{ *pulumi.OutputState }

func (AuthenticationProvidersOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*AuthenticationProviders)(nil)).Elem()
}

func (o AuthenticationProvidersOutput) ToAuthenticationProvidersOutput() AuthenticationProvidersOutput {
	return o
}

func (o AuthenticationProvidersOutput) ToAuthenticationProvidersOutputWithContext(ctx context.Context) AuthenticationProvidersOutput {
	return o
}

func (o AuthenticationProvidersOutput) ToAuthenticationProvidersPtrOutput() AuthenticationProvidersPtrOutput {
	return o.ToAuthenticationProvidersPtrOutputWithContext(context.Background())
}

func (o AuthenticationProvidersOutput) ToAuthenticationProvidersPtrOutputWithContext(ctx context.Context) AuthenticationProvidersPtrOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, v AuthenticationProviders) *AuthenticationProviders {
		return &v
	}).(AuthenticationProvidersPtrOutput)
}

func (o AuthenticationProvidersOutput) Email() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v AuthenticationProviders) *bool { return v.Email }).(pulumi.BoolPtrOutput)
}

func (o AuthenticationProvidersOutput) Google() GoogleProviderPtrOutput {
	return o.ApplyT(func(v AuthenticationProviders) *GoogleProvider { return v.Google }).(GoogleProviderPtrOutput)
}

func (o AuthenticationProvidersOutput) Web3() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v AuthenticationProviders) *bool { return v.Web3 }).(pulumi.BoolPtrOutput)
}

type AuthenticationProvidersPtrOutput struct{ *pulumi.OutputState }

func (AuthenticationProvidersPtrOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**AuthenticationProviders)(nil)).Elem()
}

func (o AuthenticationProvidersPtrOutput) ToAuthenticationProvidersPtrOutput() AuthenticationProvidersPtrOutput {
	return o
}

func (o AuthenticationProvidersPtrOutput) ToAuthenticationProvidersPtrOutputWithContext(ctx context.Context) AuthenticationProvidersPtrOutput {
	return o
}

func (o AuthenticationProvidersPtrOutput) Elem() AuthenticationProvidersOutput {
	return o.ApplyT(func(v *AuthenticationProviders) AuthenticationProviders {
		if v != nil {
			return *v
		}
		var ret AuthenticationProviders
		return ret
	}).(AuthenticationProvidersOutput)
}

func (o AuthenticationProvidersPtrOutput) Email() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *AuthenticationProviders) *bool {
		if v == nil {
			return nil
		}
		return v.Email
	}).(pulumi.BoolPtrOutput)
}

func (o AuthenticationProvidersPtrOutput) Google() GoogleProviderPtrOutput {
	return o.ApplyT(func(v *AuthenticationProviders) *GoogleProvider {
		if v == nil {
			return nil
		}
		return v.Google
	}).(GoogleProviderPtrOutput)
}

func (o AuthenticationProvidersPtrOutput) Web3() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *AuthenticationProviders) *bool {
		if v == nil {
			return nil
		}
		return v.Web3
	}).(pulumi.BoolPtrOutput)
}

type EnvironmentVariable struct {
	Name  string `pulumi:"name"`
	Value string `pulumi:"value"`
}

// EnvironmentVariableInput is an input type that accepts EnvironmentVariableArgs and EnvironmentVariableOutput values.
// You can construct a concrete instance of `EnvironmentVariableInput` via:
//
//	EnvironmentVariableArgs{...}
type EnvironmentVariableInput interface {
	pulumi.Input

	ToEnvironmentVariableOutput() EnvironmentVariableOutput
	ToEnvironmentVariableOutputWithContext(context.Context) EnvironmentVariableOutput
}

type EnvironmentVariableArgs struct {
	Name  pulumi.StringInput `pulumi:"name"`
	Value pulumi.StringInput `pulumi:"value"`
}

func (EnvironmentVariableArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*EnvironmentVariable)(nil)).Elem()
}

func (i EnvironmentVariableArgs) ToEnvironmentVariableOutput() EnvironmentVariableOutput {
	return i.ToEnvironmentVariableOutputWithContext(context.Background())
}

func (i EnvironmentVariableArgs) ToEnvironmentVariableOutputWithContext(ctx context.Context) EnvironmentVariableOutput {
	return pulumi.ToOutputWithContext(ctx, i).(EnvironmentVariableOutput)
}

// EnvironmentVariableArrayInput is an input type that accepts EnvironmentVariableArray and EnvironmentVariableArrayOutput values.
// You can construct a concrete instance of `EnvironmentVariableArrayInput` via:
//
//	EnvironmentVariableArray{ EnvironmentVariableArgs{...} }
type EnvironmentVariableArrayInput interface {
	pulumi.Input

	ToEnvironmentVariableArrayOutput() EnvironmentVariableArrayOutput
	ToEnvironmentVariableArrayOutputWithContext(context.Context) EnvironmentVariableArrayOutput
}

type EnvironmentVariableArray []EnvironmentVariableInput

func (EnvironmentVariableArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]EnvironmentVariable)(nil)).Elem()
}

func (i EnvironmentVariableArray) ToEnvironmentVariableArrayOutput() EnvironmentVariableArrayOutput {
	return i.ToEnvironmentVariableArrayOutputWithContext(context.Background())
}

func (i EnvironmentVariableArray) ToEnvironmentVariableArrayOutputWithContext(ctx context.Context) EnvironmentVariableArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(EnvironmentVariableArrayOutput)
}

type EnvironmentVariableOutput struct{ *pulumi.OutputState }

func (EnvironmentVariableOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*EnvironmentVariable)(nil)).Elem()
}

func (o EnvironmentVariableOutput) ToEnvironmentVariableOutput() EnvironmentVariableOutput {
	return o
}

func (o EnvironmentVariableOutput) ToEnvironmentVariableOutputWithContext(ctx context.Context) EnvironmentVariableOutput {
	return o
}

func (o EnvironmentVariableOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v EnvironmentVariable) string { return v.Name }).(pulumi.StringOutput)
}

func (o EnvironmentVariableOutput) Value() pulumi.StringOutput {
	return o.ApplyT(func(v EnvironmentVariable) string { return v.Value }).(pulumi.StringOutput)
}

type EnvironmentVariableArrayOutput struct{ *pulumi.OutputState }

func (EnvironmentVariableArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]EnvironmentVariable)(nil)).Elem()
}

func (o EnvironmentVariableArrayOutput) ToEnvironmentVariableArrayOutput() EnvironmentVariableArrayOutput {
	return o
}

func (o EnvironmentVariableArrayOutput) ToEnvironmentVariableArrayOutputWithContext(ctx context.Context) EnvironmentVariableArrayOutput {
	return o
}

func (o EnvironmentVariableArrayOutput) Index(i pulumi.IntInput) EnvironmentVariableOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) EnvironmentVariable {
		return vs[0].([]EnvironmentVariable)[vs[1].(int)]
	}).(EnvironmentVariableOutput)
}

type GoogleProvider struct {
	Id     string `pulumi:"id"`
	Secret string `pulumi:"secret"`
}

// GoogleProviderInput is an input type that accepts GoogleProviderArgs and GoogleProviderOutput values.
// You can construct a concrete instance of `GoogleProviderInput` via:
//
//	GoogleProviderArgs{...}
type GoogleProviderInput interface {
	pulumi.Input

	ToGoogleProviderOutput() GoogleProviderOutput
	ToGoogleProviderOutputWithContext(context.Context) GoogleProviderOutput
}

type GoogleProviderArgs struct {
	Id     pulumi.StringInput `pulumi:"id"`
	Secret pulumi.StringInput `pulumi:"secret"`
}

func (GoogleProviderArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GoogleProvider)(nil)).Elem()
}

func (i GoogleProviderArgs) ToGoogleProviderOutput() GoogleProviderOutput {
	return i.ToGoogleProviderOutputWithContext(context.Background())
}

func (i GoogleProviderArgs) ToGoogleProviderOutputWithContext(ctx context.Context) GoogleProviderOutput {
	return pulumi.ToOutputWithContext(ctx, i).(GoogleProviderOutput)
}

func (i GoogleProviderArgs) ToGoogleProviderPtrOutput() GoogleProviderPtrOutput {
	return i.ToGoogleProviderPtrOutputWithContext(context.Background())
}

func (i GoogleProviderArgs) ToGoogleProviderPtrOutputWithContext(ctx context.Context) GoogleProviderPtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(GoogleProviderOutput).ToGoogleProviderPtrOutputWithContext(ctx)
}

// GoogleProviderPtrInput is an input type that accepts GoogleProviderArgs, GoogleProviderPtr and GoogleProviderPtrOutput values.
// You can construct a concrete instance of `GoogleProviderPtrInput` via:
//
//	        GoogleProviderArgs{...}
//
//	or:
//
//	        nil
type GoogleProviderPtrInput interface {
	pulumi.Input

	ToGoogleProviderPtrOutput() GoogleProviderPtrOutput
	ToGoogleProviderPtrOutputWithContext(context.Context) GoogleProviderPtrOutput
}

type googleProviderPtrType GoogleProviderArgs

func GoogleProviderPtr(v *GoogleProviderArgs) GoogleProviderPtrInput {
	return (*googleProviderPtrType)(v)
}

func (*googleProviderPtrType) ElementType() reflect.Type {
	return reflect.TypeOf((**GoogleProvider)(nil)).Elem()
}

func (i *googleProviderPtrType) ToGoogleProviderPtrOutput() GoogleProviderPtrOutput {
	return i.ToGoogleProviderPtrOutputWithContext(context.Background())
}

func (i *googleProviderPtrType) ToGoogleProviderPtrOutputWithContext(ctx context.Context) GoogleProviderPtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(GoogleProviderPtrOutput)
}

type GoogleProviderOutput struct{ *pulumi.OutputState }

func (GoogleProviderOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GoogleProvider)(nil)).Elem()
}

func (o GoogleProviderOutput) ToGoogleProviderOutput() GoogleProviderOutput {
	return o
}

func (o GoogleProviderOutput) ToGoogleProviderOutputWithContext(ctx context.Context) GoogleProviderOutput {
	return o
}

func (o GoogleProviderOutput) ToGoogleProviderPtrOutput() GoogleProviderPtrOutput {
	return o.ToGoogleProviderPtrOutputWithContext(context.Background())
}

func (o GoogleProviderOutput) ToGoogleProviderPtrOutputWithContext(ctx context.Context) GoogleProviderPtrOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, v GoogleProvider) *GoogleProvider {
		return &v
	}).(GoogleProviderPtrOutput)
}

func (o GoogleProviderOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v GoogleProvider) string { return v.Id }).(pulumi.StringOutput)
}

func (o GoogleProviderOutput) Secret() pulumi.StringOutput {
	return o.ApplyT(func(v GoogleProvider) string { return v.Secret }).(pulumi.StringOutput)
}

type GoogleProviderPtrOutput struct{ *pulumi.OutputState }

func (GoogleProviderPtrOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**GoogleProvider)(nil)).Elem()
}

func (o GoogleProviderPtrOutput) ToGoogleProviderPtrOutput() GoogleProviderPtrOutput {
	return o
}

func (o GoogleProviderPtrOutput) ToGoogleProviderPtrOutputWithContext(ctx context.Context) GoogleProviderPtrOutput {
	return o
}

func (o GoogleProviderPtrOutput) Elem() GoogleProviderOutput {
	return o.ApplyT(func(v *GoogleProvider) GoogleProvider {
		if v != nil {
			return *v
		}
		var ret GoogleProvider
		return ret
	}).(GoogleProviderOutput)
}

func (o GoogleProviderPtrOutput) Id() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *GoogleProvider) *string {
		if v == nil {
			return nil
		}
		return &v.Id
	}).(pulumi.StringPtrOutput)
}

func (o GoogleProviderPtrOutput) Secret() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *GoogleProvider) *string {
		if v == nil {
			return nil
		}
		return &v.Secret
	}).(pulumi.StringPtrOutput)
}

type Project struct {
	Name   string `pulumi:"name"`
	Region string `pulumi:"region"`
}

// ProjectInput is an input type that accepts ProjectArgs and ProjectOutput values.
// You can construct a concrete instance of `ProjectInput` via:
//
//	ProjectArgs{...}
type ProjectInput interface {
	pulumi.Input

	ToProjectOutput() ProjectOutput
	ToProjectOutputWithContext(context.Context) ProjectOutput
}

type ProjectArgs struct {
	Name   pulumi.StringInput `pulumi:"name"`
	Region pulumi.StringInput `pulumi:"region"`
}

func (ProjectArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*Project)(nil)).Elem()
}

func (i ProjectArgs) ToProjectOutput() ProjectOutput {
	return i.ToProjectOutputWithContext(context.Background())
}

func (i ProjectArgs) ToProjectOutputWithContext(ctx context.Context) ProjectOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ProjectOutput)
}

func (i ProjectArgs) ToProjectPtrOutput() ProjectPtrOutput {
	return i.ToProjectPtrOutputWithContext(context.Background())
}

func (i ProjectArgs) ToProjectPtrOutputWithContext(ctx context.Context) ProjectPtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ProjectOutput).ToProjectPtrOutputWithContext(ctx)
}

// ProjectPtrInput is an input type that accepts ProjectArgs, ProjectPtr and ProjectPtrOutput values.
// You can construct a concrete instance of `ProjectPtrInput` via:
//
//	        ProjectArgs{...}
//
//	or:
//
//	        nil
type ProjectPtrInput interface {
	pulumi.Input

	ToProjectPtrOutput() ProjectPtrOutput
	ToProjectPtrOutputWithContext(context.Context) ProjectPtrOutput
}

type projectPtrType ProjectArgs

func ProjectPtr(v *ProjectArgs) ProjectPtrInput {
	return (*projectPtrType)(v)
}

func (*projectPtrType) ElementType() reflect.Type {
	return reflect.TypeOf((**Project)(nil)).Elem()
}

func (i *projectPtrType) ToProjectPtrOutput() ProjectPtrOutput {
	return i.ToProjectPtrOutputWithContext(context.Background())
}

func (i *projectPtrType) ToProjectPtrOutputWithContext(ctx context.Context) ProjectPtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ProjectPtrOutput)
}

type ProjectOutput struct{ *pulumi.OutputState }

func (ProjectOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*Project)(nil)).Elem()
}

func (o ProjectOutput) ToProjectOutput() ProjectOutput {
	return o
}

func (o ProjectOutput) ToProjectOutputWithContext(ctx context.Context) ProjectOutput {
	return o
}

func (o ProjectOutput) ToProjectPtrOutput() ProjectPtrOutput {
	return o.ToProjectPtrOutputWithContext(context.Background())
}

func (o ProjectOutput) ToProjectPtrOutputWithContext(ctx context.Context) ProjectPtrOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, v Project) *Project {
		return &v
	}).(ProjectPtrOutput)
}

func (o ProjectOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v Project) string { return v.Name }).(pulumi.StringOutput)
}

func (o ProjectOutput) Region() pulumi.StringOutput {
	return o.ApplyT(func(v Project) string { return v.Region }).(pulumi.StringOutput)
}

type ProjectPtrOutput struct{ *pulumi.OutputState }

func (ProjectPtrOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**Project)(nil)).Elem()
}

func (o ProjectPtrOutput) ToProjectPtrOutput() ProjectPtrOutput {
	return o
}

func (o ProjectPtrOutput) ToProjectPtrOutputWithContext(ctx context.Context) ProjectPtrOutput {
	return o
}

func (o ProjectPtrOutput) Elem() ProjectOutput {
	return o.ApplyT(func(v *Project) Project {
		if v != nil {
			return *v
		}
		var ret Project
		return ret
	}).(ProjectOutput)
}

func (o ProjectPtrOutput) Name() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Project) *string {
		if v == nil {
			return nil
		}
		return &v.Name
	}).(pulumi.StringPtrOutput)
}

func (o ProjectPtrOutput) Region() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Project) *string {
		if v == nil {
			return nil
		}
		return &v.Region
	}).(pulumi.StringPtrOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*AuthenticationProvidersInput)(nil)).Elem(), AuthenticationProvidersArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*AuthenticationProvidersPtrInput)(nil)).Elem(), AuthenticationProvidersArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*EnvironmentVariableInput)(nil)).Elem(), EnvironmentVariableArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*EnvironmentVariableArrayInput)(nil)).Elem(), EnvironmentVariableArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*GoogleProviderInput)(nil)).Elem(), GoogleProviderArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*GoogleProviderPtrInput)(nil)).Elem(), GoogleProviderArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*ProjectInput)(nil)).Elem(), ProjectArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*ProjectPtrInput)(nil)).Elem(), ProjectArgs{})
	pulumi.RegisterOutputType(AuthenticationProvidersOutput{})
	pulumi.RegisterOutputType(AuthenticationProvidersPtrOutput{})
	pulumi.RegisterOutputType(EnvironmentVariableOutput{})
	pulumi.RegisterOutputType(EnvironmentVariableArrayOutput{})
	pulumi.RegisterOutputType(GoogleProviderOutput{})
	pulumi.RegisterOutputType(GoogleProviderPtrOutput{})
	pulumi.RegisterOutputType(ProjectOutput{})
	pulumi.RegisterOutputType(ProjectPtrOutput{})
}
