name: Dev Release Workflow

on:
  release:
    types: [created]

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
  NUGET_PUBLISH_KEY: ${{ secrets.NUGET_PUBLISH_KEY }}
  PYPI_PASSWORD: ${{ secrets.PYPI_PASSWORD }}

jobs:
  build-on-ubuntu:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v') && contains(github.ref, 'dev')
    steps:
      - uses: actions/checkout@3
      - name: Install Pulumi CLI
        uses: pulumi/actions@v4
      - name: Install Pulumictl
        uses: jaxxstorm/action-install-gh-release@v1.5.0
        with:
          repo: pulumi/pulumictl
      - name: Install Go
        uses: actions/setup-go@v5
      - name: Install Node.js
        uses: actions/setup-node@v4
      - name: Install Python
        uses: actions/setup-python@v5
      - name: Install Dotnet
        uses: actions/setup-dotnet@v4
      - name: Install Java
        uses: actions/setup-java@v4
      - name: Install Graddle
        uses: gradle/actions/setup-gradle@v3
      - name : Publish NodeJs sdk
        uses : pulumi/pulumi-package-publisher@v0.0.20
        with :
          sdk: nodejs
