// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export class Authentication extends pulumi.CustomResource {
    /**
     * Get an existing Authentication resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, opts?: pulumi.CustomResourceOptions): Authentication {
        return new Authentication(name, undefined as any, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'genezio:index:Authentication';

    /**
     * Returns true if the given object is an instance of Authentication.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Authentication {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Authentication.__pulumiType;
    }

    public readonly databaseType!: pulumi.Output<string>;
    public readonly databaseUrl!: pulumi.Output<string>;
    public readonly project!: pulumi.Output<outputs.domain.Project>;
    public readonly provider!: pulumi.Output<outputs.domain.AuthenticationProviders | undefined>;
    public /*out*/ readonly region!: pulumi.Output<string>;
    public /*out*/ readonly token!: pulumi.Output<string>;

    /**
     * Create a Authentication resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: AuthenticationArgs, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            if ((!args || args.databaseType === undefined) && !opts.urn) {
                throw new Error("Missing required property 'databaseType'");
            }
            if ((!args || args.databaseUrl === undefined) && !opts.urn) {
                throw new Error("Missing required property 'databaseUrl'");
            }
            if ((!args || args.project === undefined) && !opts.urn) {
                throw new Error("Missing required property 'project'");
            }
            resourceInputs["databaseType"] = args ? args.databaseType : undefined;
            resourceInputs["databaseUrl"] = args ? args.databaseUrl : undefined;
            resourceInputs["project"] = args ? args.project : undefined;
            resourceInputs["provider"] = args ? args.provider : undefined;
            resourceInputs["region"] = undefined /*out*/;
            resourceInputs["token"] = undefined /*out*/;
        } else {
            resourceInputs["databaseType"] = undefined /*out*/;
            resourceInputs["databaseUrl"] = undefined /*out*/;
            resourceInputs["project"] = undefined /*out*/;
            resourceInputs["provider"] = undefined /*out*/;
            resourceInputs["region"] = undefined /*out*/;
            resourceInputs["token"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(Authentication.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * The set of arguments for constructing a Authentication resource.
 */
export interface AuthenticationArgs {
    databaseType: pulumi.Input<string>;
    databaseUrl: pulumi.Input<string>;
    project: pulumi.Input<inputs.domain.ProjectArgs>;
    provider?: pulumi.Input<inputs.domain.AuthenticationProvidersArgs>;
}
